[package]
name = "mezon-active-windows"
version.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc = { workspace = true }
cocoa = { workspace = true }
core-foundation = { workspace = true }

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
x11rb = { version = "0.13", features = ["screensaver"] }
