[package]
name = "mezon-cli"
version.workspace = true
license.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
mezon-mcp.workspace = true
mezon-native.workspace = true
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
