[package]
name = "mezon-app"
version.workspace = true
edition = "2024"
default-run = "mezon"

[[bin]]
name = "mezon"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform = { workspace = true, features = ["font-kit"] }
mezon-ui.workspace = true
mezon-store.workspace = true
mezon-native.workspace = true
mezon-updater.workspace = true
mezon-client.workspace = true
dotenvy = "0.15"
flume.workspace = true
reqwest_client.workspace = true
tokio.workspace = true
futures.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
dirs.workspace = true
serde.workspace = true

[build-dependencies]
woff2-patched = "0.4.0"
